project:
  type: website
  output-dir: docs

website:
  title: "Jesse Harrison"
  navbar:
    left:
      - text: Projects
        href: projects.qmd
      - text: Publications
        href: publications.qmd
      - text: Teaching
        href: teaching.qmd
      - text: Posts
        href: posts.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual

