---
title: "Publications"
---

**Further details**

-   [Google Scholar](https://scholar.google.com/citations?user=ZqkvSqsAAAAJ)
-   [ORCID](https://orcid.org/0000-0002-4877-4684)

## Peer-reviewed articles

<small>

23\. [Year-long microbial succession on microplastics in wastewater: chaotic dynamics outweigh preferential growth](https://www.mdpi.com/2076-2607/10/9/1775). 2022. Tagg AS, Sperlea T, Labrenz M, **Harrison JP**, Ojeda JJ, Sapp M. *Microorganisms* 10:1775.

22\. [16S and 18S rRNA gene metabarcoding provide congruent information on the responses of sediment communities to eutrophication](https://www.frontiersin.org/articles/10.3389/fmars.2021.708716/abstract). 2021. **Harrison JP**, Chronopoulou M, Salonen I, Jilbert T, Koho K. *Frontiers in Marine Science* 8:708716.

21\. [Putative degraders of low-density polyethylene-derived compounds are ubiquitous members of plastic-associated bacterial communities in the marine environment](https://sfamjournals.onlinelibrary.wiley.com/doi/10.1111/1462-2920.15232). 2020. Pinto M, Zenner PP, Langer TM, **Harrison JP**, Simon M, Varela MM, Herndl GJ. *Environmental Microbiology* 22: 4779-4793.

20\. [Microplastic monitoring at different stages in a wastewater treatment plant using reflectance micro-FT-IR imaging](https://www.frontiersin.org/articles/10.3389/fenvs.2020.00145/full). 2020. Tagg AS, Sapp M, **Harrison JP**, Sinclair CJ, Bradley E, Ju-Nam Y, Ojeda JJ. *Frontiers in Environmental Science* 8:145.

19\. [Sample collection and return from Mars: optimising sample collection based on the microbial ecology of terrestrial volcanic environments](https://link.springer.com/article/10.1007/s11214-019-0609-7). 2019. Cockell CS, McMahon S, Lim DSS, Rummel J, Stevens A, Hughes SS, Nawotniak SEK, Brady AL, Marteinsson V, Martin-Torres J, Zorzano MP, **Harrison JP**. *Space Science Reviews* 215: 44.

18\. [A low diversity microbiota inhabits extreme basaltic terrains and their fumaroles: implications for the exploration of Mars](https://www.liebertpub.com/doi/full/10.1089/ast.2018.1870). 2019. Cockell CS, **Harrison JP**, Stevens A, Payler SJ, Hughes SS, Nawotniak SEK, Brady AL, Elphic RC, Haberle CW, Sehlke A, Beaton K, Abercromby A, Schwendner P, Wadsworth J, Landenmark H, Cane R, Dickinson AW, Nicholson N, Perera L, Lim DSS. *Astrobiology* 19: 284--299.

17\. [Biodegradability standards for carrier bags and plastic films in aquatic environments: a critical review](http://rsos.royalsocietypublishing.org/content/5/5/171792). 2018. **Harrison JP**, Boardman C, O'Callaghan K, Delort A-M, Song J. *Royal Society Open Science* 5: 171792.

16\. [The UK Centre for Astrobiology: a virtual astrobiology centre. Accomplishments and lessons learned, 2011-2016](http://online.liebertpub.com/doi/pdfplus/10.1089/ast.2017.1713). 2018. Cockell CS, Biller B, Bryce C, Direito S, Forgan D, Fox-Powell M, **Harrison JP**, Landenmark H, Nixon S, Payler SJ, Rice K, Samuels T, Schwendner P, Stevens A, Nicholson N, Wadsworth J. *Astrobiology* 18: 224--243.

15\. [Vibrational spectroscopy for imaging single microbial cells in complex biological samples](http://journal.frontiersin.org/article/10.3389/fmicb.2017.00675/abstract). 2017. **Harrison JP**, Berry D. *Frontiers in Microbiology* 8: 675.

14\. [Astrobiology as a framework for investigating antibiotic susceptibility: a study of *Halomonas hydrothermalis*](http://rsif.royalsocietypublishing.org/content/14/126/20160942). 2017. **Harrison JP**, Angel R, Cockell CS. *Journal of the Royal Society Interface* 14: 20160942.

13\. [Fenton's reagent for the rapid and efficient isolation of microplastics from wastewater](http://pubs.rsc.org/en/content/articlehtml/2017/cc/c6cc08798a). 2017. Tagg AS, **Harrison JP**, Ju-Nam Y, Sapp M, Bradley EL, Sinclair CJ, Ojeda JJ. *Chemical Communications* 53: 372--375.

12\. [Rock geochemistry induces stress and starvation responses in the bacterial proteome](http://onlinelibrary.wiley.com/doi/10.1111/1462-2920.13093/abstract). 2016. Bryce CC, Le Bihan T, Martin SF, **Harrison JP**, Bush T, Spears B, Moore A, Leys N, Byloos B, Cockell CS. *Environmental Microbiology* 18: 1110--1121.

11\. [Mapping limits to life on Earth](http://astrogeo.oxfordjournals.org/content/57/2/2.15.full). 2016. Freeman K, **Harrison JP**, Dobinson L, Cockell CS, McKenzie R, Wyllie D, Nixon SL. *Astronomy & Geophysics* 57: 2.15--2.17.

10\. [Salinity influences the response of *Halomonas hydrothermalis* to artificial fossilization by evaporative silicification](http://www.tandfonline.com/doi/full/10.1080/01490451.2015.1045634). 2016. **Harrison JP**, Aggarwal SD, Cockell CS. *Geomicrobiology Journal* 33: 377--386.

9\. [AstRoMap European Astrobiology Roadmap](https://www.liebertpub.com/doi/full/10.1089/ast.2015.1441). 2016. Horneck G, Walter N, Westall F, Grenfell JL, Martin WF, Gomez F, Leuko S, Lee N, Onofri S, Kleomenis T, Raffaele S, Pilat-Lohinger E, Ernesto P, **Harrison JP**, Rull F, Muller C, Strazzulla G, Brucato JR, Rettberg P, Capria MT. *Astrobiology* 16: 201--243 (Published as a special issue).

8\. [Habitability: a review](http://online.liebertpub.com/doi/pdfplus/10.1089/ast.2015.1295). 2016. Cockell CS, Bush T, Bryce CC, Direito S, Fox-Powell M, **Harrison JP**, Lammer H, Landenmark H, Martin-Torres J, Nicholson N, Noack L, O'Malley-James J, Payler SJ, Rushby A, Samuels T, Schwendner P, Zorzano MP. *Astrobiology* 16: 89--117.

7\. [Aerobically respiring prokaryotic strains exhibit a broader temperature--pH--salinity space for cell division than anaerobically respiring and fermentative strains](http://rsif.royalsocietypublishing.org/content/12/110/20150658). 2015. **Harrison JP**, Dobinson L, Freeman K, McKenzie R, Wyllie D, Nixon SL, Cockell CS. *Journal of the Royal Society Interface* 12: 20150658.

6\. [Identification and quantification of microplastics in wastewater using FPA-based reflectance micro-FT-IR imaging](https://pubs.acs.org/doi/full/10.1021/acs.analchem.5b00495). 2015. Tagg AS, Sapp M, **Harrison JP**, Ojeda JJ. *Analytical Chemistry* 87: 6032--6040.

5\. [Reduction of the temperature sensitivity of *Halomonas hydrothermalis* by iron starvation combined with microaerobic conditions](http://aem.asm.org/content/81/6/2156.full). 2015. **Harrison JP**, Hallsworth JE, Cockell CS. *Applied and Environmental Microbiology* 81: 2156--2162.

4\. [Rapid bacterial colonization of low-density polyethylene microplastics in coastal sediment microcosms](https://bmcmicrobiol.biomedcentral.com/articles/10.1186/s12866-014-0232-4). 2014. **Harrison JP**, Schratzberger M, Sapp M, Osborn AM. *BMC Microbiology* 14: 232.

3\. [The limits for life under multiple extremes](http://www.sciencedirect.com/science/article/pii/S0966842X13000206). 2013. **Harrison JP**, Gheeraert N, Tsigelnitskiy D, Cockell CS. *Trends in Microbiology* 21: 204--212.

2\. [The applicability of reflectance micro-Fourier-transform infrared spectroscopy for the detection of synthetic microplastics in marine sediments](http://www.sciencedirect.com/science/article/pii/S0048969711013969). 2012. **Harrison JP**, Ojeda JJ, Romero-González ME. *Science of the Total Environment* 416: 455--463.

1\. [Interactions between microorganisms and marine microplastics: a call for research](http://www.ingentaconnect.com/content/mts/mtsj/2011/00000045/00000002/art00003). 2011. **Harrison JP**, Sapp M, Schratzberger M, Osborn AM. *Marine Technology Society Journal* 45: 12--20 *Invited paper.*

</small>

## Book chapters, technical reports and policy documents

<small>

3\. [Open research data and methods. National policy and executive plan by the higher education and research community for 2021–2025: Policy component 2 - open access to research methods and infrastructures](https://edition.fi/tsv/catalog/book/669). 2023. Open Science Coordination in Finland / The Committee for Public Information (TJNK) and Federation of Finnish Learned Societies (TSV). *National policy document providing recommendations for the openness of research methods and infrastructures.*

2\. [Microplastic-associated biofilms: a comparison of freshwater and marine environments](https://link.springer.com/chapter/10.1007/978-3-319-61615-5_9). 2018. **Harrison JP**, Hoellein TJ, Sapp M, Tagg AS, Ju-Nam Y, Ojeda JJ. In: *Freshwater Microplastics* (Wagner M, Lambert S, eds). *The Handbook of Environmental Chemistry* 58, pp. 181--201. Springer. *Invited book chapter.*

1\. [Review of standards for biodegradable plastic carrier bags](https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/485904/carrier-bag-biodegradable-report-2015.pdf). 2015. Department for Environment, Food and Rural Affairs. *Summary report to UK Parliament based on Technical Advisory Group output.*

</small>

## Project deliverables

<small>

3. [BioDT D1.2 - Data management plan](https://ec.europa.eu/research/participants/documents/downloadPublic?documentIds=080166e5f44bcefb&appId=PPGMS). 2022. **Harrison JP**, Allas A-L, Koivula H, Blankett R.

2. [PerMedCoE D1.2 - Software best practices and optimisation interim report](https://permedcoe.eu/wp-content/uploads/2023/04/D1.2_Software-best-practices-and-optimisation-interim-report_V1.0_20220331.pdf). 2022. **Harrison JP**, Montagud A, Noël V, Rodríguez-Mier P, Kratochvil M.

1. [PerMedCoE D2.2 - Midterm code release](https://permedcoe.eu/wp-content/uploads/2023/03/D2.2_Mid-Term-Code-Release_v1.0_20220330.pdf). 2022. **Harrison JP**, Conejero C, Gorroñogoitia J, Rodríguez-Mier P.

## Selected presentations, interviews and posters

-   [BioDT Podcast Episode 1](https://open.spotify.com/episode/0xtMliwmq78GuDUxRWKwFJ?si=1ffe77c2017947a6). 2024. *Interview on project from scientific coordination perspective.*

-   [Biodiversity Digital Twin: general project vision](https://zenodo.org/record/8075657). 2023. Harrison JP. *Poster on Zenodo.*

-   [BioDT: a digital twin for advanced simulation, modelling and prediction capabilities](https://doi.org/10.5281/zenodo.6841357). 2022. Harrison JP. *Presentation slides on Zenodo.*

</small>

## PhD thesis

<small>

[The spectroscopic detection and bacterial colonisation of synthetic microplastics in coastal marine sediments](http://etheses.whiterose.ac.uk/2643/). 2012. Harrison JP. PhD Thesis, Department of Animal and Plant Sciences, The University of Sheffield, UK.

</small>
